language: node_js
node_js: node

addons:
  ssh_known_hosts:
    secure: "t9FmEP+1HTDL81jpNoRzjoD3BHbCgPljTWArX3mbdCnVsy6zD3WG4KFtdT9DzF2kdRpMiF8iRtBRAM62Zt5wmlkrKCIktxbGqq6MsTVZnIvKrSn5SCkHvLlXgvy4duyosOy8x+R9VYC/3i8yEdoAVjK5L0o15OWcQQxuGtm62Q6gfG2u6cPGlhZ9aXmdjvvHt+eQxcAeCJEy6ZN0pM4fcCP2KVQYB88pH7JnE4MtJTcXE1fdgKfk7I2Vw6yiEokimlIjUamzdz4xlYszNZqyPAzHJckpKpdUHZQcbyCIIroP6hNg+DlacqVTP54oDwDvRjOvOareCkZr0vxQHOn2vqoc7LwiBR8RMQfbHy+h8Tq8vCVZ8gZeqwkbqdPsysNbs1HdroQiVXbS+4130gvJufqhJqr4ynbrZaWOehSUM6DbvwYioW8WmivIwsiU2YARAtKc+/JFoykbf1mpj/dJogUhX3dXlosBJBg/DJ2G3KZZRBHZo3B8U13OcnZvYXzAv+RddIcYGNSTkBsHu7yDcR1DclSR4DNUGElpOtb3W3dXmAqK/6Dnta82iummeQNmttSzoJ+FWufRKPSMUE+BXJzUfjyCwnH5IY7c096KlgdI4/i5LHBN+8bMJbce8FJbWHEzyo2TywQ6mkFGaz+HznoACpVhROVhVpyh+JHNzDY="

before_install:
  - openssl aes-256-cbc -K $encrypted_f339be35999a_key -iv $encrypted_f339be35999a_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - npm ci
  - cp src/styles/_config.example.scss src/styles/_config.scss
script: npm run build
after_success: "[[ $TRAVIS_BRANCH == \"master\" && $TRAVIS_PULL_REQUEST == \"false\" ]] && .travis/deploy.sh"
