language: node_js
node_js: node

addons:
  ssh_known_hosts:
    secure: "ndf03h91fNbeaKiG14K19JthpxgxyXM96YeeE7AdpjNUNomOopfbpfs2CU2A9deE9jCrZbO5ZrjUcLXbOijzjWm9Njz0RHYEoH8RFGuOi6qg2KLUWxEVG7znL/oLqCIA7ysoso2lfBpTLRR1MSti6nx6d3+9XkymXa7Y+6oEkFf+S3+nf2tctlj2Aby79FQJekUXwOT8a0Ccu/+P82MKwa2mOdzraAV+TXH7AmdRbDoWMHjn7HGTUGRBFIbBjQxZ15jmDCPbN3HY+H/ri5uSYDcG5+Bv8DbFKehFf1v2dB++zSPYXGr23QYXdMUbHC5paSK3A+m1cfyFomQ0lt2IUzFGtX0ZLMJVVCZ/GQBjfHauoKM9a4OwGdAb1cJyTIQdcrzsiR4fStZC0ZRoMBnmVzhIY+Z0+lv0ownANvKgvZubSi5W7YcdBeI8Y9i28RwgGBfV2qFzaAR9gFfgPMEnn5ZwgotzeaM0GZjy424r5+w+9S50EYlmLWeTN95wW9W2B7Yvi8LUMXx7AilheJcUp4lxVe8jItx/6uumSD6mwVKVDhohhV2eZPq9SjVBgVqn8aE+mTkdEv4YCWQIGAoLgqj97mH9Iunn8AqM0+4f2485qPQLgS5y6u0eF4nr0jILbSIQFMgPlVlvwwM8X/EU01bN3ygdcCzMODjDXLkOZV4="

before_install:
  - openssl aes-256-cbc -K $encrypted_f339be35999a_key -iv $encrypted_f339be35999a_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - npm ci
  - cp src/styles/_config.example.scss src/styles/_config.scss
script: npm run build
after_success: "[[ $TRAVIS_BRANCH == \"master\" && $TRAVIS_PULL_REQUEST == \"false\" ]] && .travis/deploy.sh"
