name: Pull request

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14 # Current LTS
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npx ng lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14 # Current LTS
      - name: Install dependencies
        run: npm ci
      - name: Create configs
        run: cp src/styles/_config.example.scss src/styles/_config.scss
      - name: Build in production mode
        run: npm run build:prod
