name: MyMICDS CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Create configs
        run: cp src/styles/_config.example.scss src/styles/_config.scss
      - name: Build in production mode
        run: npm run build:prod

  deploy:
    # even though the workflow should only run if we're on master in the first place,
    # explicitly check before running the deploy in case we broaden the workflow events
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Decrypt secret files
        run: ./.github/scripts/decrypt_secrets.sh
        env:
          FILE_DECRYPT_KEY: ${{ secrets.FILE_DECRYPT_KEY }}
          FILE_DECRYPT_IV: ${{ secrets.FILE_DECRYPT_IV }}
      - name: Deploy to remote server
        run: ./.github/scripts/deploy.sh
        env:
          IP: ${{ secrets.DEPLOY_SSH_IP }}
          PORT: ${{ secrets.DEPLOY_SSH_PORT }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
